# scripts/run_real_hcg_inventory.py

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from app.services.sweet_engine.adapters.hcg_packet_adapter import (
    build_inventory_from_packet_manifest,
)


PROJECT_ROOT = Path(__file__).resolve().parents[1]

DEFAULT_OUTPUT_DIRECTORY = (
    PROJECT_ROOT
    / "data"
    / "sweet_evaluation"
    / "real_packets"
)


def load_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        raise FileNotFoundError(
            f"Manifest not found: {path}"
        )

    with path.open("r", encoding="utf-8") as file:
        payload = json.load(file)

    if not isinstance(payload, dict):
        raise ValueError(
            f"Expected JSON object in manifest: {path}"
        )

    return payload


def write_inventory_json(
    inventory,
    output_directory: Path,
) -> Path:
    output_directory.mkdir(
        parents=True,
        exist_ok=True,
    )

    output_path = (
        output_directory
        / f"{inventory.packet_id}-sweet-inventory.json"
    )

    with output_path.open(
        "w",
        encoding="utf-8",
    ) as file:
        json.dump(
            inventory.to_manifest_dict(),
            file,
            indent=2,
            ensure_ascii=False,
            default=_json_default,
        )

    return output_path


def print_page_results(inventory) -> None:
    print("\nPage-by-page SWEET results")
    print("-" * 110)

    header = (
        f"{'Page':<6}"
        f"{'Raw type':<30}"
        f"{'Final type':<30}"
        f"{'Confidence':<12}"
        f"{'Source':<18}"
        f"{'Review'}"
    )

    print(header)
    print("-" * 110)

    for page in inventory.pages:
        print(
            f"{page.page_number:<6}"
            f"{page.raw_document_type:<30}"
            f"{page.final_document_type:<30}"
            f"{page.confidence:<12.2f}"
            f"{page.classification_source.value:<18}"
            f"{'YES' if page.requires_review else 'NO'}"
        )


def print_summary(inventory) -> None:
    summary = inventory.summary()

    print("\nSWEET inventory summary")
    print("-" * 50)

    for key, value in summary.items():
        print(f"{key}: {value}")


def _json_default(value: Any) -> Any:
    """
    Support enums if any remain after dataclass conversion.
    """

    if hasattr(value, "value"):
        return value.value

    raise TypeError(
        f"Object of type {type(value).__name__} "
        "is not JSON serializable"
    )


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Build a SWEET PageInventory from an existing "
            "ClaimsBridge packet manifest."
        )
    )

    parser.add_argument(
        "--manifest",
        required=True,
        help=(
            "Path to the manifest.json generated by "
            "classify-and-segregate."
        ),
    )

    parser.add_argument(
        "--output-dir",
        default=str(DEFAULT_OUTPUT_DIRECTORY),
        help="Directory for the SWEET inventory JSON.",
    )

    return parser.parse_args()


def main() -> None:
    args = parse_arguments()

    manifest_path = Path(args.manifest).resolve()
    output_directory = Path(args.output_dir).resolve()

    manifest = load_json(manifest_path)

    inventory = build_inventory_from_packet_manifest(
        manifest,
        run_context_resolution=True,
    )

    print_page_results(inventory)
    print_summary(inventory)

    output_path = write_inventory_json(
        inventory,
        output_directory,
    )

    print(f"\nSWEET inventory JSON: {output_path}")


if __name__ == "__main__":
    main()