# app/services/sweet_engine/enums.py

from enum import Enum


class PageProcessingStatus(str, Enum):
    PENDING = "PENDING"
    CLASSIFIED = "CLASSIFIED"
    CONTEXT_INFERRED = "CONTEXT_INFERRED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    UNREADABLE = "UNREADABLE"
    BLANK = "BLANK"
    ERROR = "ERROR"


class ClassificationSource(str, Enum):
    VISION = "VISION"
    OCR_RULE = "OCR_RULE"
    RULE = "RULE"
    CONTEXT = "CONTEXT"
    RULE_GUIDED_RECOVERY = "RULE_GUIDED_RECOVERY"
    HUMAN_REVIEW = "HUMAN_REVIEW"
    UNRESOLVED = "UNRESOLVED"


class PageBoundaryType(str, Enum):
    UNKNOWN = "UNKNOWN"
    START = "START"
    CONTINUATION = "CONTINUATION"
    END = "END"
    SINGLE_PAGE = "SINGLE_PAGE"


class ReviewPriority(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ReviewReasonCode(str, Enum):
    LOW_CLASSIFICATION_CONFIDENCE = "LOW_CLASSIFICATION_CONFIDENCE"
    AMBIGUOUS_DOCUMENT_TYPE = "AMBIGUOUS_DOCUMENT_TYPE"
    POSSIBLE_CONTINUATION_PAGE = "POSSIBLE_CONTINUATION_PAGE"
    DOCUMENT_BOUNDARY_UNCERTAIN = "DOCUMENT_BOUNDARY_UNCERTAIN"
    PATIENT_IDENTIFIER_MISMATCH = "PATIENT_IDENTIFIER_MISMATCH"
    MULTIPLE_DOCUMENT_TYPES_DETECTED = "MULTIPLE_DOCUMENT_TYPES_DETECTED"
    LOW_OCR_QUALITY = "LOW_OCR_QUALITY"
    UNREADABLE_PAGE = "UNREADABLE_PAGE"
    POSSIBLE_WRONG_GROUP = "POSSIBLE_WRONG_GROUP"
    MISSING_EXPECTED_DOCUMENT = "MISSING_EXPECTED_DOCUMENT"
    DUPLICATE_PAGE = "DUPLICATE_PAGE"
    CLASSIFICATION_ERROR = "CLASSIFICATION_ERROR"